source 'https://rubygems.org'

gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.12.3'
gem 'rails', '~> 5.2.3'
gem 'sequel', '~> 5.20.0'

group :development, :test do
  gem 'rspec-rails', '~> 3.8.2'
  gem 'byebug'
end
